name: "Build resume"
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build resume
        # Dirty repo workaround. Wait until NixOS/nix/pull/5758 is released.
        run: nix build .\?rev=$(git rev-parse HEAD)

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: result/*.pdf
